// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqf7gWadJv40fJA3nnhzDcV4SxqkWwv5A',
    appId: '1:868410584429:web:e66d0c96f1c69362e97e64',
    messagingSenderId: '868410584429',
    projectId: 'ecommerce-app-3d7b0',
    authDomain: 'ecommerce-app-3d7b0.firebaseapp.com',
    storageBucket: 'ecommerce-app-3d7b0.firebasestorage.app',
    measurementId: 'G-ZDG86CW55Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCSK4RT-P7don7PS2S4t-otKrTWKUQO3I',
    appId: '1:868410584429:android:0a5c47fc3e72e7f9e97e64',
    messagingSenderId: '868410584429',
    projectId: 'ecommerce-app-3d7b0',
    storageBucket: 'ecommerce-app-3d7b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl6Yaj5KxcnhN8DNzr03DTfSHGO2XdvYU',
    appId: '1:868410584429:ios:ed9ca667db099b6fe97e64',
    messagingSenderId: '868410584429',
    projectId: 'ecommerce-app-3d7b0',
    storageBucket: 'ecommerce-app-3d7b0.firebasestorage.app',
    androidClientId: '868410584429-jbh9ljksqbkp12coj7d66428sul6osu9.apps.googleusercontent.com',
    iosClientId: '868410584429-mrk5aq9559n49fi0g1tn3jh8mabla83a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAdmin',
  );
}
